In [21]:
# import libraries
import os
import sys
import arcpy
import numpy as np
from arcpy.sa import *


item = 'Encamat//plocha_4_2_compo_1'

def validation_matrix(composite):
    composite_ras = arcpy.Raster(item)

    # analyse it
    ## cellsize specification
    cellSize = composite_ras.meanCellWidth
    Cell_Size = str(cellSize)+" "+str(cellSize)

    ## additional values specification
    lowerLeft = arcpy.Point(composite_ras.extent.XMin,composite_ras.extent.YMin)

    ## export to numpy array
    composite_array = arcpy.RasterToNumPyArray(composite_ras,nodata_to_value=0)

    no_no = 0
    no_sheet = 0
    no_rill = 0
    sheet_no = 0
    sheet_sheet = 0
    sheet_rill = 0
    rill_no = 0
    rill_sheet = 0
    rill_rill = 0

    unique_valid = []
    unique_sort = []

    i, j, k, l = 0, 0, 0, 0
    limit_x = composite_array.shape[2]
    limit_y = composite_array.shape[1]
    steps = limit_x * limit_y
    area_no = 0.0001
    area_sheet = 0.0001
    area_rill = 0.0001

    for step in range(steps):
        valid = composite_array[0][j, i]
        sort = composite_array[1][j, i]

    #     if valid == 0:
    #         pass

        if valid not in unique_valid:
            unique_valid.append(valid)

        if sort not in unique_sort:
            unique_sort.append(sort)

        if valid == 99:
    #     elif valid == 99:
            area_no += 1
            if sort == 99:
                no_no += 1
            elif sort == 88:
                no_sheet += 1
            else:
                no_rill += 1

        elif valid == 88:
            area_sheet += 1
            if sort == 99:
                sheet_no += 1
            elif sort == 88:
                sheet_sheet += 1
            else:
                sheet_rill += 1

        else:
            area_rill += 1
            if sort == 99:
                rill_no += 1
            elif sort == 88:
                rill_sheet += 1
            else:
                rill_rill += 1

        i += 1
        if i == limit_x:
            j +=1
            i = 0
        if j+1 == limit_y:
            j = 0
            break

    validation_matrix = numpy.empty((3, 3))
    validation_matrix[0:1, 0:1] = int(round(no_no/area_no, 2) * 100)
    validation_matrix[1:2, 0:1] = int(round(no_sheet/area_no, 2) * 100)
    validation_matrix[2:3, 0:1] = int(round(no_rill/area_no, 2) * 100)
    validation_matrix[0:1, 1:2] = int(round(sheet_no/area_sheet, 2) * 100)
    validation_matrix[1:2, 1:2] = int(round(sheet_sheet/area_sheet, 2) * 100)
    validation_matrix[2:3, 1:2] = int(round(sheet_rill/area_sheet, 2) * 100)
    validation_matrix[0:1, 2:3] = int(round(rill_no/area_rill, 2) * 100)
    validation_matrix[1:2, 2:3] = int(round(rill_sheet/area_rill, 2) * 100)
    validation_matrix[2:3, 2:3] = int(round(rill_rill/area_rill, 2) * 100)

    print(validation_matrix)

    return validation_matrix

    # print(int(round(no_no/area_no, 2) * 100), int(round(sheet_no/area_sheet, 2) * 100), int(round(rill_no/area_rill, 2) * 100))
    # print(int(round(no_sheet/area_no, 2) * 100), int(round(sheet_sheet/area_sheet, 2) * 100), int(round(rill_sheet/area_rill, 2) * 100))
    # print(int(round(no_rill/area_no, 2) * 100), int(round(sheet_rill/area_sheet, 2) * 100), int(round(rill_rill/area_rill, 2) * 100))

#     print(unique_valid)
#     print(unique_sort)



In [22]:
validation_matrix('Encamat//plocha_4_2_compo_1')

[[14. 23.  0.]
 [45. 42.  1.]
 [41. 35. 99.]]


array([[14., 23.,  0.],
       [45., 42.,  1.],
       [41., 35., 99.]])

In [20]:
validation_matrix = numpy.empty((3, 3))
validation_matrix[0:1, 0:1] = int(round(no_no/area_no, 2) * 100)
validation_matrix[1:2, 0:1] = int(round(no_sheet/area_no, 2) * 100)
validation_matrix[2:3, 0:1] = int(round(no_rill/area_no, 2) * 100)
validation_matrix[0:1, 1:2] = int(round(sheet_no/area_sheet, 2) * 100)
validation_matrix[1:2, 1:2] = int(round(sheet_sheet/area_sheet, 2) * 100)
validation_matrix[2:3, 1:2] = int(round(sheet_rill/area_sheet, 2) * 100)
validation_matrix[0:1, 2:3] = int(round(rill_no/area_rill, 2) * 100)
validation_matrix[1:2, 2:3] = int(round(rill_sheet/area_rill, 2) * 100)
validation_matrix[2:3, 2:3] = int(round(rill_rill/area_rill, 2) * 100)
                             
print(validation_matrix)

[[14. 23.  0.]
 [45. 42.  1.]
 [41. 35. 99.]]


In [13]:
int(round(sheet_sheet/area_sheet, 2) * 100)

42